### ISSUE TITLE
Passing down `className`?

### ISSUE THREAD

**Issue by Connorelsea** [paypal/glamorous#112]
- `glamorous` version: 3.13.3
- `glamor` version: 2.20.25
- `react` version: 15.5.4

**The problem:**

To have the styles apply, you have to pass `className` onto the div from the props. Is there a specific reason this is the case? It seems like boilerplate and I can not find this being documented in the docs.

**Relevant code:**

Render method of `ToggleButtonGroup`

```javascript
  render() {
    return (
      <div value={this.getCurrentSelection()} className={this.props.className}>
        {React.Children.map(this.props.children, (child, i) => (
          <child.type
            // irrelevant props given
          >
            {child.props.children}
          </child.type>
        ))}
      </div>
    )
  }
```

Styling an instance of `ToggleButtonGroup` in another component.

```javascript
const StyledToggleButtonGroup = glamorous(ToggleButtonGroup)({
  backgroundColor: "red",
})
```

![image](https://cloud.githubusercontent.com/assets/1844458/26209413/5947716c-3bb2-11e7-9884-1b4d93cecd2f.png)

The only reason className is on that div is because it is passed down

**Comment by kentcdodds** [comment]
Hey @Connorelsea 👋 

You're correct, you _do_ need to utilize the `className` that glamorous passes you. As noted in the docs [here](https://github.com/paypal/glamorous#glamorous-1):

> This is done by forwarding a className prop to the component you tell it to render

and [here](https://github.com/paypal/glamorous#glamorouscomponentfactory):

> This is accomplished by generating a className for the styles you give and forwarding that className onto the rendered element. So if you're wrapping a component you intend to style, you'll need to make sure you accept the className as a prop and apply it to where you want the styles applied in your custom component (normally the root element).

The reason this is necessary for custom components is because glamor generates the style sheet and gives us a class name to utilize those styles, but we have no way to apply those to your component. There are also cases where you wouldn't want that applied directly to the root element, but some other child element in your component.

Actually, components generated by glamorous (like `glamorous.div()` or `<glamorous.Article />`) do this className forwarding already, so if you're wrapping a glamorous-generated component, then you don't need to worry about it. What's more is glamorous will actually merge any glamor-generated styles together in a predictable way so you never worry about specificity as mentioned [here](https://github.com/paypal/glamorous#using-classname).

All this said, it appears that it's not clear enough in the docs. What do you think could be done to improve this? Maybe an additional example? Or more clear docs? Or maybe a "gotchas" section?

Whatever you think is best, why don't you open up a pull request with that and we can discuss that further. Thanks!

**Comment by Connorelsea** [comment]
Thank you, this makes sense.

I think the reason I and some of my peers passed over this because the docs are fairly complex in some areas. This is actually good and useful when digging deep into how this works, but I think there is some room for more introductory/"quick start" material covering the basics.

I was also confused at first because when I did a `glamorous(Link)` when the Link was from `react-router`, nothing needed to be done and it just worked.

This sentence below, to me upon initial read, made me think any child of a glamorous component had the className automatically applied to it. Especially after seeing the behavior of "glamorous.a", "glamorous.div" etc

"This is done by forwarding a className prop to the component you tell it to render."

I am working on an internal medium doc for some developers at my office to quickly get started with glamorous and could definitely make this external or help incorporate similar wording into the current docs.

**Comment by kentcdodds** [comment]
That's great! I need to get back to working on the glamorous website. I've got a pretty good start [here](https://codesandbox.io/s/59XX9B1MR). But more needs to be done and I need to actually make it a thing....

**Comment by Connorelsea** [comment]
Very WIP and not yet published, but this is what I'm working with. https://medium.com/@Connorelsea/introduction-to-glamorous-currently-wip-e33006d236ba

**Comment by Connorelsea** [comment]
Actually @kentcdodds , I don't think I am entirely sure why it is not just passed down automatically to the custom component. This may be an extreme lapse in thought for me, but after reading through some of the code, I'm just not getting it for some reason. It seems to list `className` as something that should be forwarded here: https://github.com/paypal/glamorous/blob/master/src/react-props.js

Why not just apply the className to a custom component if possible automatically?

**Comment by kentcdodds** [comment]
It is be passed automatically, but you have to accept it and do something with it. For example:

```jsx
const MyComp = (props) => <div></div>

<MyComp className="hi" />
```

In this case, `MyComp` will render a div, but the `className` will not be applied because it's not doing anything with the props it's given. That's your job as the author of `MyComp`. So you have to change your component to:

```jsx
const MyComp = (props) => <div className={props.className}></div>

<MyComp className="hi" />
```

Or, what's more common is:

```jsx
const MyComp = (props) => <div {...props} />

<MyComp className="hi" />
```

Which is why glamorous filters out non-dom props for you, because if I used that component like:

```jsx
<MyComp big={true} />
```

Then I'd get a warning, but if you wrap it as a glamorous component, then glamorous will filter it out.

Does that make sense?

**Comment by kentcdodds** [comment]
Moving this issue to https://github.com/kentcdodds/glamorous-website/issues/221
