### ISSUE TITLE
Allow importing built-in glamorous components

### ISSUE THREAD

**Issue by souporserious** [paypal/glamorous#123]
I think it would be awesome to allow something like ```import { Div, Span } from 'glamorous'```. It's not a huge deal to just pull it off below, but I get questions about this and was wondering if there is a possible solution.

It seems that we will need some type of [pre-build](https://gist.github.com/FezVrasta/a29f3d8f6a715993a05ba1d24a241d3b) or babel-transform to accomplish this, I'm not really familiar in this area, but I'm willing to help out wherever I might be able to.

**Comment by kentcdodds** [comment]
Thanks for the issue @souporserious!
Yep, I think a pre-build is the best way to do this. I'm thinking that we could just insert it at the bottom of the [`glamorous.es.js`](https://unpkg.com/glamorous@3.15.0/dist/glamorous.es.js) file because only tree-shaking-capable tools should pick that one up and those things will get tree-shaken so we don't need to worry about adding a bunch of extra bloat to the final bundle which is great.

So my thought is it'll be something like:

```javascript
export const Div = glamorous.Div
export const Span = glamorous.Span
// ... etc
```

To make this work, we could just add a `&& node other/concat-exports.js` where we'd read in the list of DOM elements from [dom-elements.js](https://github.com/paypal/glamorous/blob/master/src/dom-elements.js) and generate the string.

Should hopefully be fairly straightforward. Anyone wanna work on this?

**Comment by marzelin** [comment]
@kentcdodds I'm on it.
