### ISSUE TITLE
Add flow type definitions

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#177]
Because TypeScript shouldn't have all the fun :wink:

I'm pretty new to Flow. Anyone with experience wanna help out? I think having the existing TypeScript definitions could really help :) And in our case we could probably add the flow definitions directly in the source because that would be really handy as well and we're already stripping them out with the React preset :+1: Though, I'm not sure whether consumers would be able to use those. Maybe those are two separate issues (adding flow to the codebase and adding type definitions for consumers to use?) I don't know! Help wanted!

**Comment by ErikCupal** [comment]
Sounds great! I'll definitely help. I have not tried Flow yet, but it's 90% the same as Typescript as far as I know.

**Comment by kentcdodds** [comment]
Sounds awesome!

**Comment by kentcdodds** [comment]
Thanks! :)

**Comment by pbomb** [comment]
I would love to see this and could probably help out as well. I think [this post](http://javascriptplayground.com/blog/2017/01/npm-flowjs-javascript/) did a good job advocating for the approach of running the code through babel + creating `.js.flow` files next to the source files so that consumers would get the benefits of flow types.

**Comment by kentcdodds** [comment]
Fantastic! Looks really great. Thanks for ya'lls willingness to pitch in :)

**Comment by suchipi** [comment]
I'm also interested in helping; is there a plan for dividing up the codebase so we don't duplicate work and step on each other's toes? Or would it be better if only one person worked on this?

**Comment by luke-john** [comment]
I'd be keen for the typescript and flow typings to follow a similar structure.

This should help keep the two in sync and make the initial setup of flow typing a bit easier.

Happy for the typescript typing to get restructured as part of this if there's a pattern more suitable.

**Comment by torifat** [comment]
@kentcdodds How about this one? https://babeljs.io/docs/plugins/transform-flow-comments/

**Comment by kentcdodds** [comment]
I think that @pbomb's suggest would support consumers as well. But if this works, it seems simpler! Anyone wanna try your hand at a PR for that? @suchipi, you seemed interested. Would you like to? Whoever wants to, just mention here that you've started working on it when you start

**Comment by suchipi** [comment]
Yeah, I'm interested. I will take a look this evening, using babel-plugin-transform-flow-comments.

**Comment by suchipi** [comment]
As you can see from the referenced commits, I've started work on this; I'm not done yet, but if you want to follow along, you can [view the comparison between my branch and master](https://github.com/paypal/glamorous/compare/master...suchipi:flow). I'll submit a PR once I'm ready.

**Comment by kentcdodds** [comment]
Looking good! Thanks!

**Comment by suchipi** [comment]
I have continued work on this, but am hitting a wall:

In flow, [it is considered an error to add properties to objects when those properties are not in their type definition](https://flow.org/en/docs/types/objects/#toc-sealed-objects). [`create-glamorous.js`](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/create-glamorous.js) and [`index.js`](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/index.js) rely on this style of programming relatively extensively, though:
* [`glamorousComponentFactory`](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/create-glamorous.js#L40) calls [`withTheme`](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/with-theme.js#L12), which creates a [`ThemedComponent`](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/with-theme.js#L16) class. It then [changes the `propTypes` property on this class to something else](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/create-glamorous.js#L82) (which flow considers to be an error, I'm not sure why though) and [uses `getGlamorousComponentMetadata` to add 6 new static properties to it](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/create-glamorous.js#L99): `styles`, `comp`, `rootEl`, `forwardProps`, `withComponent`, and `isGlamorousComponent`. Flow considers this to be an error, because those 6 properties are not declared as statics in ThemedComponent.

* `index.js` mixes in [`glamorousComponentFactory`s](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/index.js#L18) and [glamorous components](https://github.com/paypal/glamorous/blob/f55f15767b84de619eafab1c879843f1ff2dd64b/src/index.js#L38) for all the HTML and SVG tag names onto the glamorous function that is exported. Flow considers this an error, because the function wasn't defined with those properties on it.

This isn't unsolvable, but the ways I can think of to work around this have pros and cons:
#### Option 1: Put $FlowFixMe in all the places where flow dislikes what we're doing.
Flow lets you put a comment with the prefix `$FlowFixMe` in front of an error to suppress it.

Pros:
* Requires little change to how the code is organized

Cons:
* Flow bails out on tracking types for a node with a $FlowFixMe comment on it, treating it like `any` instead. So if we have to do this in a ton of places (or a few central places), it defeats the purpose of typing everything.

#### Option 2: Only put type definitions in the files that are easy to add type definitions to
So no `@flow` comment or type definitions in `index.js` or `create-glamorous.js`, but we try to put them everywhere else.

Pros:
* Doesn't feel like a hack

Cons:
* The files that aren't easy to add type definitions to are the most important ones to have type definitions for, since they explain how the module's main export works.

#### Option 3: Declare all the potential properties an object could have ahead of time
For example, ThemedComponent would have type annotations for all the static properties that a `glamorousComponentFactory` could add to it, even though it otherwise doesn't need to know about them.

Pros:
* This is the way flow wants you to do it

Cons:
* This might make the code more confusing (especially in `with-theme.js`). It will also make the code less DRY because we will need to duplicate all the tag name-based properties that the main export has on it (though I think the typescript definitions already had to do this, so it isn't unprecedented). 
* I think there are a few places where we add properties to external React Component classes, and we couldn't put the statics on those classes since they don't live in our codebase. 

#### Option 4: "Trick" flow into being okay with what we're doing
It's considered dangerous, but you can [type-cast through `any`](https://flow.org/en/docs/types/casting/#toc-type-casting-through-any) to tell flow that one value is of any arbitrary type. We could create a "virtual" type for GlamorousComponent and the package export (GlamorousInterface), and tell flow that it's working with those things instead.
Pros:
* withTheme doesn't need to know which properties glamorousComponentFactory is going to add to it
* This would be a bit better aligned with the typescript typings

Cons:
* Since you cast through any, flow can't warn you anymore if the value you're working with doesn't satisfy the type you're casting it into. So it kinda defeats the purpose of using flow in the package's source.

#### Option 5: Reorganize the codebase so that the properties are added in a way that makes flow happy
It would probably look like:
* wrap withTheme with a function that uses [bounded polymorphism](https://flow.org/blog/2015/03/12/Bounded-Polymorphism/) to declare the additional statics the resulting ThemedComponent will have. 
* Do something similar with the element tag names, though the path forward with that is less clear. We might have to apply the technique in Option 4 just for the package export.

Pros:
* Feels the cleanest and makes flow happy

Cons:
* Will introduce otherwise-unnecessary abstraction just to make flow happy
* Will make the codebase harder to read for people unfamiliar with flow.
* Will be hard to rebase onto, so it will be harder to get merged, so there will be more risk of the work never making it into master

#### Option 6: Don't put type definitions in the source code, and submit a library definition to [flow-typed](https://github.com/flowtype/flow-typed) instead
Pros:
* We don't have to worry about what the code's actually like
* If the maintainers of glamorous aren't interested in learning flow, it will make the codebase easier to understand

Cons:
* If the code no longer matches the library definition in flow-typed, flow won't tell us (so the same problem as Option 4, kinda)
* All my work will go down the drain :sweat_smile: 

I think Option 6 is probably the best approach in this case, but Option 5 could be applied if the maintainers are interested in learning/maintaining/wrangling flow.

**Comment by suchipi** [comment]
As an aside, I have reached out to the flow team about this issue here: https://github.com/facebook/flow/issues/4193

**Comment by kentcdodds** [comment]
Wow! Thanks for all the work on this. I haven't read it quite yet and I'm going to be gone for a week, but I'll just say that I'd prefer to avoid alerting the user experience in favor of adding types (even if it means we don't type everything or have to do less ergonomic things in our codebase). I'd also like to try and do things the "right" way with flow.

Thanks again!

**Comment by suchipi** [comment]
So after some thought, I think we can fix the first problem (where glamorousComponentFactory modifies the ThemedComponent class it receives), by making it extend ThemedComponent instead of mutating it. Then it can declare all the statics it's going to want on the subclass, without polluting ThemedComponent.

For the second problem (the named exports of the module are mixed in dynamically), I think we could leverage Option 3 or 4. That's not the end of the world since no internal flowtype checking is going to happen beyond that point. Option 3 would guarantee type safety at the expense of needing to list every property (all the html/svg tag names, etc). Option 4 wouldn't guarantee type safety at the library/main export boundary, but that might not be the end of the world.

**Comment by kentcdodds** [comment]
> extend ThemedComponent instead of mutating it

Actually I think that would make it so we don't have to do [this weirdness](https://github.com/paypal/glamorous/blob/master/src/with-theme.js#L62-L71) which would be awesome.

RE: option 3

> It will also make the code less DRY because we will need to duplicate all the tag name-based properties that the main export has on it

I'm not concerned about this because that list will pretty much never change, so it wont be hard to maintain.

> we add properties to external React Component classes

Not sure I follow. Could you elaborate?

I think that Option 3 sounds the best. It's what flow wants us to do and unless I'm missing something the downsides aren't all that bad :smile:

**Comment by kentcdodds** [comment]
Actually, I wonder if we could do something like [this](https://github.com/paypal/glamorous/pull/131) for the flow types 🤔 adding the ones for the tags as a build-step rather than having them in the source...

**Comment by suchipi** [comment]
That would work; we'd generate the types we'd write with Option 3 instead of putting them in the codebase; rad 😃.

Regarding "we add properties to external React Component classes":

I'm trying to remember what I meant 😅 I think I was looking at the static `comp` property, but I'm not sure. I was probably referring to the 6 statics that get added, but looking back on them now, I don't see where they would be added to some other component, it seems like they'd only ever change the ThemedComponent.

By the way, this wasn't entirely clear from reading the codebase... is the point of the `comp` property to prevent re-wrapping something that's already a glamorous component?

**Comment by kentcdodds** [comment]
> is the point of the `comp` property to prevent re-wrapping something that's already a glamorous component?

Bingo :+1:

**Comment by kentcdodds** [comment]
To be more clear, it's because we're merging everything that's interesting from one glamorous component to the next anyway (styles mostly), so no reason to render multiple levels of components for that.

**Comment by tgallacher** [comment]
If it's not too late you might also consider `flow-copy-source` plugin which automatically creates the `.flow` files in the output dir for you. 

see: https://github.com/AgentME/flow-copy-source

Also, happy to lend a hand if needed.

**Comment by kentcdodds** [comment]
@luke-john has done such an amazing job working on the TypeScript typings that if we could benefit from that work with the flow typings that would be amaaaaaazzzzzzzzzzzing!

**Comment by kentcdodds** [comment]
> Also, happy to lend a hand if needed.

@tgallacher if you wanna open a PR so we can see what that would look like, please do!

**Comment by kentcdodds** [comment]
Ah... I misunderstood what you were talking about... For some reason I thought you were referencing a project that could convert TypeScript typings to Flow types... My bad...

I'm not convinced I want to add flow to the source code. I'd rather keep it separate like TS is... Thanks though!

**Comment by kentcdodds** [comment]
I'm trying to clean things up a bit. I'm going to close this issue until someone is motivated to push this along :)
