### ISSUE TITLE
Can @media be used in theme?

### ISSUE THREAD

**Issue by tomsowerby** [paypal/glamorous#179]
More of a question that I'm struggling to find the answer to:
Can we use media within a theme?

An adjusted example from the readme: https://codesandbox.io/s/k5ozjJro6
FontSize is applied, but the color switches are not.

It could be a useful way of avoiding media queries in children.

**Comment by kentcdodds** [comment]
Yes, can definitely do what you're trying to do. Will come back when I'm at a computer

**Comment by kentcdodds** [comment]
So, you have a `SubTitle` component that's using the `style` prop to style an element. You don't want to use the `style` prop to style things normally because they don't support media queries, pseudo selectors, and have perf issues. Instead, depending on your use-case, you can use `glamor` directly, or wrap your component in `glamorous`. Here's a solution that might give you some insight: https://codesandbox.io/s/GkRqW9VL

A key takeaway from this example is that you can pass any number of arguments to a `glamorousComponentFactory` (like `glamorous.h1`). Doing this will cause `glamor` to merge the styles together properly. This is one of the key elements that makes glamorous so composable.

If you feel like our docs could be improved WRT media queries/theming, please contribute examples/improvements to the [new website we're working on](https://github.com/kentcdodds/glamorous-website).

I'm going to go ahead and close this, but feel free to ask further questions :)

**Comment by tomsowerby** [comment]
So that's how you do it!
It makes sense now that I see it, pass the object that contains the media query around rather than the specific attribute.
Excellent response, and very quick. Thank you.

**Comment by kentcdodds** [comment]
You're welcome! A great way to say thank you is to contribute back! Any contributions appreciated 😀 There are a few issues ready to be implemented on both the website and the core lib. Let me know if you need help getting started 👍
