### ISSUE TITLE
Dev tool source map.

### ISSUE THREAD

**Issue by gt3240** [paypal/glamorous#194]
First of all, loving glamorous, great job guys.  My question is does Glamorous support source mapping?

**Comment by kentcdodds** [comment]
Hi @gt3240! Glad you're enjoying glamorous. Because glamorous is built in glamor, the place to look for information on source maps is in glamor docs/issues. I saved you a search and you'll find some discussion for it [here](https://github.com/threepointone/glamor/issues/238). TL;DR: Can't do sourcemaps with generated code. This is unfortunate. However I think that it's not a huge deal because you can generally figure out what component is responsible for what you're looking at pretty easily (especially with [the babel plugin](https://www.npmjs.com/package/babel-plugin-glamorous-displayname) and [this config](https://github.com/paypal/glamorous#usedisplaynameinclassname)) and finding the styles for that is easy because it's right there with the component. So I'm not too bummed that sourcemaps aren't supported.

Would you care to add a FAQ section to the README explaining this briefly?

**Comment by gt3240** [comment]
Thanks @kentcdodds for getting back to me.  I kind of knew this not being possible due to the css is generated in javascript, but just wanted to confirm it.  I will be happy to add the FAQ section =).
