### ISSUE TITLE
Change priority order of overrides?

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#195]
Hey everyone! We need a vote on something! Right now, [here's](https://github.com/paypal/glamorous/blob/a4fc674c879362058d424523026ad4ec747f9b73/src/get-glamor-classname.js#L41) how we determine priority of the various ways you can apply styles to a glamorous element. Here's a quick rundown of what these are:

**`...styles`**

```javascript
const MyDiv = glamorous.div({marginTop: 20})
```

**`parentGlamorStyles`**

```jsx
const parentGlamorStyles = glamor.css({marginTop: 20})
// the important bit is that it's a glamor-generated className that's applied
// via the `className` prop
<glamorous.Div className={parentGlamorStyles} />
```

**`cssOverrides `**

```jsx
// the props that are CSS values
<glamorous.Div marginTop={20} />
```

**`cssProp`**

```jsx
<glamorous.Div css={{marginTop: 20}} />
```

Priority goes from right to left in that array (so `...styles` has least priority). I'm 99% positive that `...styles` should stay where it's at, but I'm less certain about the order of the others. I have a co-worker who's building something where he found it confusing that `className` did not take highest priority.

[Here's](https://codesandbox.io/s/jRpOjkpLy) an example, and I would like a vote:

```jsx
function App() {
  // Which would you expect?
  //   (all of them have: {paddingTop: 1, paddingRight: 2, paddingBottom: 3})
  // least priority => greater priority
  // 1. css props, className, css == {marginTop: 2, marginRight: 3, marginLeft: 3}
  // 2. css props, css, className == {marginTop: 2, marginRight: 3, marginLeft: 2}
  // 3. css, className, css props == {marginTop: 1, marginRight: 1, marginLeft: 2}
  // 4. css, css props, className == {marginTop: 2, marginRight: 1, marginLeft: 2}
  // 5. className, css, css props == {marginTop: 1, marginRight: 1, marginLeft: 3}
  // 6. className, css props, css == {marginTop: 1, marginRight: 3, marginLeft: 3}
  //
  // today, it's #6
  return (
    <glamorous.Div

      // css props
      paddingTop={1} // will definitely be applied
      maringTop={1} // overrided by className?
      marginRight={1} // override by css?
      
      // className that's generated by glamorous
      className={glamor.css({
        paddingRight: 2, // will definitely be applied
        maringTop: 2, // overrided by css props?
        marginLeft: 2, // overrided by css?
      })}
      
      // css
      css={{
        paddingBottom: 3, // will definitely be applied
        marginRight: 3, // overrided by css props?
        marginLeft: 3, // overrided by className?
      }}

    />
  );
}
```

So, here's how the voting will go. Because we don't have number emoji reactions (Dear GitHub), I'm going to post an individual comment for each of these options. Please leave an emoji reaction:

- :+1: Yes, this is what we should do
- :-1: No, please don't do this

If you don't really care, leave a :confused: reaction on this original comment.

Thanks friends!

**Note:** I would release any change as a major version bump. I don't expect it to impact many people because combining these methods of styles is not terribly common, but I think it'd be better to play it safe. Also I want to push a small breaking change for the `config` anyway :)

**Another note:** It's more common to accept the `className` as a prop to your component. I would be surprised to see anyone doing what I'm doing up there with `className={glamor.css({})}`. Don't do that :)

**Comment by kentcdodds** [comment]
1. css props, className, css == {marginTop: 2, marginRight: 3, marginLeft: 3}

**Comment by kentcdodds** [comment]
2. css props, css, className == {marginTop: 2, marginRight: 3, marginLeft: 2}

**Comment by kentcdodds** [comment]
3. css, className, css props == {marginTop: 1, marginRight: 1, marginLeft: 2}

**Comment by kentcdodds** [comment]
4. css, css props, className == {marginTop: 2, marginRight: 1, marginLeft: 2}

**Comment by kentcdodds** [comment]
5. className, css, css props == {marginTop: 1, marginRight: 1, marginLeft: 3}

**Comment by kentcdodds** [comment]
6. className, css props, css == {marginTop: 1, marginRight: 3, marginLeft: 3}

(This is what it is today), so a vote for this is a vote for not changing anything.

**Comment by danielberndt** [comment]
My intuition is that something that kinda looks like inline-styles should overwrite a className. Just like it happens in the real DOM: `<span class="with-margin" style="margin: 3px;"/>` (`style` trumps `class` here)

**Comment by danielberndt** [comment]
Preferring `className` might also lead to non-consistent results depending on where you take the class names from: (If I understand the underlying technology correctly)

```jsx
<button className="btn" border="none"/> // will have no border if `btn` was defined in a non-glamor stylesheet, even if classNames takes precedence
```

```jsx
const btn = css({border: "1px solid", background: "transparent"})

<button className={btn} border="none"/> // will have a border if className takes precedence
```

**Comment by kentcdodds** [comment]
Great points @danielberndt!

**Comment by kentcdodds** [comment]
@danielberndt, based on your comment, I think you may have misunderstood the examples for voting. Priority goes from right to left, meaning # 4 would make className trump all, whereas, # 5 and # 6 make className least significant.

**Comment by danielberndt** [comment]
Ah oops! Good thing that this voting system is non-anonymous 😅 
I just fixed my vote. 

I voted for `css` trumping `css-props` because `css` feels like an escape hatch that should only be used in exceptional cases. And in these cases it should override everything else.

Consider this case:

```
<Div color="red" css={{":hover":"blue"}}/>
```

If I'm not too mistaken wrt. specificity, this would mean that the `hover` definition would have no effect if its rule is put before the `color="red"` rule.

Something I (and I guess a lot of people) will find very confusing.

**Comment by kentcdodds** [comment]
I feel the same way. Though with your example, those would merge together as expected given either case 😉

**Comment by danielberndt** [comment]
Ah I wasn't aware of glamor doing the Right Thing under the hood :)

In that case I guess it doesn't matter too much what trumps what, since most `css` definitions will be some kind of merge-able stuff that takes precedence anyway. But then it will be just consistent to always give `css` definitions precedence, I think.

**Comment by braposo** [comment]
The way I see it is that `css` is the equivalent to the (inline) `style` prop so should have priority above all. For that reason `className` should have the least priority as `css props` can also be understood a variation of inline styles. So `className` < `css props` < `css` < `style`.

It's also interesting to see that `css props` get so much attention, I always thought of them as some kind of a nice thing to have (a la [jsxstyle](https://github.com/smyte/jsxstyle)) but not really that useful for the majority of users since most people would rely on writing a css-like object and feeding it to the `css` prop.

If `css props` have priority over `css` there's also the potential issue of being forced on using `css prop` if some library author decides to use that. For example, imagine this component is part of some package:
```jsx
<Component margin={16} padding={8} />
```
If I'm going to use that on my app and `css props` have priority over `css` I couldn't do this:
```jsx
import Component from "package";
...
<Component css={{ margin: 10, padding: 2 }} />
```
as the original `margin` and `padding` would always have priority. 

This of course depends a lot on the implementation and it's also valid the other way around, but since using `css` is the main approach to overriding a glamorous component styles throughout the entire documentation I think that making a change like this would probably confuse a lot of people as well.

I wouldn't mind having `css props` over `css` if there was some kind of escape hatch (like `importantCSS` prop?) so there would always be a solution for the case I highlighted above without having to rely on `style` prop that doesn't have the same capabilities.

**Comment by kentcdodds** [comment]
Yep, I'm with you @braposo :+1: I'm in favor of `className` < `css props` < `css` < `style`

Thanks everyone for your input! I'd like to call this order out in the docs. Could someone open a PR for that? Could probably add it to the new FAQ that was just added: #196

**Comment by braposo** [comment]
Well playing the devil's advocate straight away (sorry 😆) just to say that it would be easier to override the styles if `css props` had priority over `css` than the other way around. Let's see an example with `css props` having priority over `css`:

```jsx
const styles = { margin: 2, padding: 3 }

// base with css props
<Component margin={1} padding={1} />

// override with css doesn't work
<Component  css={styles} />

// override with spread props works
<Component  {...styles} />

// override with css props works
<Component  margin={2} padding={3} />
```
on the other hand if `css` has priority over `css props` (the current implementation):
```jsx
const styles = { margin: 2, padding: 3 }

// base with css
<Component css={{ margin: 1, padding: 1}} />

// override with css works
<Component  css={styles} />

// override with spread props doesn't work
<Component  {...styles} />

// override with css props doesn't work and there's no way to make it work if you want to use it
<Component  margin={2} padding={3} />
```

Bottom-line, in the current implementation if someone uses `css` it doesn't allow you to override the same properties with `css props`. Whereas if `css props` has priority over `css` the change that is required for it to work is not that much given the way that `jsx` converts the object to props.

I'm still not totally sure about it, but maybe `css props` over `css` would actually make sense for these simpler examples. The problem I think is with more complex style objects involving hover states and media queries that wouldn't work by just spreading to props.

So yeah, I stick with my initial opinion! 🤣

**Comment by kentcdodds** [comment]
Problem is that it's impossible to do hover/pseudo states with `css prop`, so if you wanted to override that you'd have trouble (though maybe it doesn't matter because those would be defined as part of the `css` prop anyway 🙃)

Here's a good API for both defining your styles as `css` and accepting overrides:

```javascript
function MyOverrideableComponent({css: overrides, ...rest}) {
  return (
    <glamorous.Div margin={20} color="red" css={[{':hover': {color: 'blue'}}, overrides]} />
  )
}
```

I think it's a little known fact that the `css` prop can accept anything you can pass to the glamorousComponentFactory (`styles` in `glamorous.div(...styles)`) which is a function, array, or object :)

**Comment by braposo** [comment]
Yeah that's what I meant in my last paragraph, I totally agree with you!

I use the array all the time, it's probably my default template to create glamorous components to be honest (and probably the main reason why I use glamorous over styled-components). I agree that maybe being more explicit to what `css` supports would make it more obvious.

(you're missing sending the `rest` to the component but it's a great example 👍 )

**Comment by kentcdodds** [comment]
> (you're missing sending the `rest` to the component but it's a great example <g-emoji alias="+1" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" ios-version="6.0" title=":+1:">👍</g-emoji> )

😅 fixed

**Comment by kentcdodds** [comment]
Moving this issue to https://github.com/kentcdodds/glamorous-website/issues/221
