### ISSUE TITLE
use html-element-attributes

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#23]
Right now we've got our own list of html-element-attributes. But we should probably rely on another package that will keep itself updated. So it was suggested in #8 that we use https://github.com/wooorm/html-element-attributes from @wooorm

It doesn't have all the svg attributes (maybe that's something @wooorm would be willing to support?). And it also doesn't have the react-specific props so we'll probably want to keep those too. But for some of this we could simplify [this file](https://github.com/paypal/glamorous/blob/f75fd4556edf826c927e6ffba20a7f950229b133/src/should-forward-property.js) a bit by using that. Pretty much just need a refactor of that file to replace `htmlProps` with that file's stuff. One thing that `shouldForwardProperty` accepts is a `tagName` which is great because it means we can leverage the knowledge of tag-specific props that html-element-attributes has to be more specific about which props to forward.

I think we should probably add some unit tests for that file as well so it's more clear what that module is capable of/responsible for.

If anyone wants to take this on, let us know!

**Comment by jackyho112** [comment]
Hello @kentcdodds, I have been following you since I watched your webpack course. I also read your blog post and watched your videos on open source project contribution. 

I do want to contribute to open source projects much more often than how much I am doing now. I believe this issue is a good opportunity and I think I can handle it. With that said, may I give this issue a go?

**Comment by kentcdodds** [comment]
Absolutely! Let me know how I can help!

**Comment by jackyho112** [comment]
Thanks! 

For checking html props, do you want me to take into account the tag name? That means `isHtmlProp` will only check if the property name exists in the global attributes and the attributes that belong to that tag in `html-element-attributes`. If so, I will have to add more attributes to `svgProps` because `html-element-attributes` does not include SVG as a tag and some SVG attributes are missing in `svgProps`.

Otherwise, I will simply set `htmlProps` to all the html attributes in `html-element-attributes` and everything else will stay the same.

**Comment by kentcdodds** [comment]
Yes, that's actually one of the benefits of going with html-element-attributes is that the attributes are scoped to the tag name and we have that (most of the time) so we can do a better job of determining which props to forward to the underlying element. So, to address your comments/questions:

> That means isHtmlProp will only check if the property name exists in the global attributes and the attributes that belong to that tag in html-element-attributes.

Perfect :+1:

>  I will have to add more attributes to svgProps because html-element-attributes does not include SVG as a tag and some SVG attributes are missing in svgProps.

Also perfect :+1:

Thanks!

**Comment by jackyho112** [comment]
Thanks for the reply!

Three questions I have right now:

- I tried to do `import htmlElementAttributes from 'html-element-attributes'` but `rollup` gives me an error. I think it has to do with it only knowing how to import ES modules and excluding anything in `node-modules` in the current setup. Sorry, I am not totally familiar with `rollup`. Do you want me to change the setting necessary to make it work? Or can I simply use `require`?

- I am also trying to write some tests for `should-forward-property.js`. It obviously would be quite substantial for the tests to cover every single scenario. Maybe we could just write a few examples that cover the general scenarios to be tested for now? 

- In the main function for `should-forward-property.js`, it will always forward a property to the react component if the `tagName` is not a string. I am not 100% sure why. Could you explain a little bit on that?

**Comment by paulmolluzzo** [comment]
This might be helpful for listing `svg` attributes: https://github.com/alexmingoia/svg-attributes

> I tried to do import htmlElementAttributes from 'html-element-attributes' but rollup gives me an error. I think it has to do with it only knowing how to import ES modules and excluding anything in node-modules in the current setup. Sorry, I am not totally familiar with rollup. Do you want me to change the setting necessary to make it work? Or can I simply use require?

See https://github.com/paypal/glamorous/pull/26#discussion_r110428820. This is the same issue and they used `require` to solve, so I think we're OK there.

Also, if you've already branched off to start working be sure to pull in the latest changes since #26 was merged and is related to this issue. (If you didn't do that already of course. 😄 )

**Comment by jackyho112** [comment]
@paulmolluzzo 

Thank you for the reminder! And I will take a look at https://github.com/alexmingoia/svg-attributes.

**Comment by kentcdodds** [comment]
>  Maybe we could just write a few examples that cover the general scenarios to be tested for now?

Yep, just cover some general scenarios :+1:

> it will always forward a property to the react component if the `tagName` is not a string.

Glad you asked, we should have a test for this to demonstrate the reason it is this way and make sure it stays this way. Here's a use case that hopefully will help explain:

```javascript
import glamorous from 'glamorous'
import ThirdPartyComponent from './third-party-component'

const MyStyledThirdPartyComponent = glamorous(ThirdPartyComponent)({/* styles */})

<MyStyledThirdPartyComponent />
```

In this case, the [`rootEl`](https://github.com/paypal/glamorous/blob/12938594070b16de9fe70c3728371726451aea52/src/index.js#L101) is set to `componentsComp`which will be `ThirdPartyComponent`. And then [when we determine which props to forward](https://github.com/paypal/glamorous/blob/12938594070b16de9fe70c3728371726451aea52/src/index.js#L195), we're forwarding `ThirdPartyComponent` (which is not a string like `'div'` or `'span'`, but is actually a Function). In that case, we want to forward _all_ props.

Perhaps we could add logic to [`splitProps`](https://github.com/paypal/glamorous/blob/12938594070b16de9fe70c3728371726451aea52/src/index.js#L185-L204) to not even do the `reduce` if the `rootEl` is not a string because we should forward all the props anyway. But in any case, it'd probably be good to preserve this behavior in `should-forward-property.js`.

Does that help?

Thanks a bunch!

**Comment by kentcdodds** [comment]
Hey @jackyho112, once [this](https://github.com/paypal/glamorous/pull/31) is merged, you'll want to rebase your branch onto the latest from `master` and you'll be able to import json files :+1:

**Comment by jackyho112** [comment]
@kentcdodds Thanks for the reply. That was helpful and I will definitely take it into account. Also, thanks for the reminder. I will rebase my branch.

**Comment by wooorm** [comment]
Hi folks! 👋 

1. In some other threads I saw that maybe svg tag-names wouldn’t be supported out of the box, does that affect whether a package like `html-element-attributes` (scoped to tag-names) is needed?

2. As this project uses HTML attributes, and not DOM properties (e.g., `class` instead of `className`, `rel` instead of `relList`, `for` instead of `htmlFor`), is a package that does that needed? I previously made a module that does that, based on React’s internal code: [`property-information`](https://github.com/wooorm/property-information), but I think it contains more info than needed, so I’m all for making/finding a new module that translates DOM properties to HTML attribute names.

**Comment by kentcdodds** [comment]
I realized that the package had originally included svg tag names as well, so that's what we went with in #26 (thank you for the packages!)

> As this project uses HTML attributes, and not DOM properties (e.g., class instead of className, rel instead of relList, for instead of htmlFor),

That's a good point! I hadn't considered it but we can't _quite_ just use a list of valid html attributes and call it good because React is a little different in some cases. I think a package that can filter React props based on tag name is what we really need. I don't think we need anything that translates DOM properties to HTML attribute names. What we need is basically something like `html-element-attributes` (that includes svg) that has a mapping of tag names to their valid _React_ props.

Anyone wanna make a package like that?

**Comment by jackyho112** [comment]
@kentcdodds Is it cool if I look into it? My branch is supposed to implement a package like that into the library anyway. Since we have decided that `html-element-attributes` is not the optimal package, I should be responsible for making a suitable one. I don't think it will be that complicated.

**Comment by kentcdodds** [comment]
Sounds perfect

**Comment by jackyho112** [comment]
The react doc says 'React supports all data-* and aria-* attributes as well as these attributes'. Should we just include that logic in `should-forward-property.js`?

**Comment by kentcdodds** [comment]
I think we do actually... 🤔

**Comment by jackyho112** [comment]
Nvm. We do. 😄

**Comment by kentcdodds** [comment]
Thanks for your help @jackyho112!
