### ISSUE TITLE
TS Definitions are a little overwhelming

### ISSUE THREAD

**Issue by probablyup** [paypal/glamorous#295]
I've been working on various benchmarks for styled components, emotion, glamorous, etc in VS Code and the defs for glamorous tend to be too verbose  -- at least for me.

<img width="611" alt="screen shot 2017-08-21 at 3 25 48 am" src="https://user-images.githubusercontent.com/570070/29507951-75adc5aa-8620-11e7-9c4f-4c706341ad55.png">

Due to them going to a second page and just generally taking up a ton of space, it sometimes inhibits keyboard usage. For instance, if you press the down arrow while that tooltip is open, it gets captured and pages down the giant list of available properties instead of going to the next line.

I definitely appreciate types being provided, but perhaps they could be slimmed a bit?

**Comment by luke-john** [comment]
hey @probablyup, the parameter hints are definitely a bit much for some parts of the typings.

I've got the following setting in my vscode user settings which means I rarely see them, but it would be great to simplify some.

```json
{
    "editor.parameterHints": false
}
```

One of the easy wins here would be to use interfaces instead of types where possible.  A few places where types are used were simply to cut down on the work of writing the same things over and over.

ie. 

```
export type StyleArgument<Properties, Props> =
  | Partial<Properties>
  | string
  | StyleFunction<Properties, Props>
  | StyleArray<Properties, Props>
```

Unfortunately this has lead to the un ideal size of parameter hints.

I'll try and spend some time identifying low hanging fruit to improve this in the coming week and setup a tracking issue for these.

**Comment by kentcdodds** [comment]
Thanks! This would be great to improve. I have the same issue on Codesandbox. It's a tiny bit annoying. cc @CompuIves

**Comment by CompuIves** [comment]
Now deploying an option to use CodeMirror or to disable Automatic Type Acquisition! 😄

**Comment by luke-john** [comment]
@probablyup I ended up making the changes to improve this as it's a pretty big annoyance in the following pr.

https://github.com/paypal/glamorous/pull/301

Related to this PR, I've opened up a seperate issue for comments to get added to the typings to help users when using the typings.

https://github.com/paypal/glamorous/issues/302
