### ISSUE TITLE
Glamorous Typings do not include WithConfig 

### ISSUE THREAD

**Issue by soltran** [paypal/glamorous#337]
Typescript Version: 2.4.1

Just trying to use [https://github.com/bernard-lin/babel-plugin-glamorous-displayname](Babel Plugin Glamorous Displayname
) so that there are better display names while debugging and snapshot testing

What happened:

I got a type error when I added the babel plugin

```TypeError: glamorous_1.default.withConfig is not a function```

Reproduction:

1. Add glamorous-displayName as a babel plugin
2. Run your code

Suggested solution:

Update the typing for glamorous. I shall make a PR for this soon.

**Comment by Ailrun** [comment]
Which loader did you use?

**Comment by luke-john** [comment]
Hey @soltran, thanks for the issue.

Whilst a pr to add the `withConfig` to the definitions would be welcome, if you're able to provide a minimal reproduction or some more details that would be great as I don't think this is an issue with the typings as that error message looks like a runtime js type issue rather than a typescript compiler message.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
