### ISSUE TITLE
fix shouldClassNameUpdate to work with React@>=16

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#368]
I think our use of `this` inside the glamorous function is the problem. But I had to skip this test when upgrading dependencies:

https://github.com/paypal/glamorous/blob/140534516927772c5ddde33d524e53a8e00c1938/src/__tests__/index.should-class-name-update.js#L64-L131

I don't use this feature so I'm not going to have time to work on this any time soon. If anyone else would like to pick it up though that'd be great :)

**Comment by raingerber** [comment]
It seems like this feature still works, but the test is broken from enzyme 3.x. The problem is with `wrapper.update` - in previous versions of `enzyme`, that would trigger a render cycle, but that's apparently no longer the case: https://github.com/airbnb/enzyme/issues/1405. I can open a PR to fix the test though (so it doesn't rely on `update`).

**Comment by kentcdodds** [comment]
Ok that's great news! Thanks. I'd love a PR 👍

**Comment by raingerber** [comment]
😀PR here: https://github.com/paypal/glamorous/pull/393
