### ISSUE TITLE
Empty <style> tag

### ISSUE THREAD

**Issue by davincho** [paypal/glamorous#375]
* `glamorous` version: 4.11.2
* `glamor` version: 2.20.40
* `react` version: 16.2.0

What you did:

I am using glamorous with create-react-app. During development I can change the css properties of css classes generated by glamorous. In production something weird happens:

<img width="468" alt="screen shot 2018-01-17 at 15 55 11" src="https://user-images.githubusercontent.com/2635143/35049007-0539e0fc-fb9f-11e7-8031-83cdbba0eaf7.png">

If you are looking for the original class (by clicking on style tag right to the class name), you will get this:

<img width="434" alt="screen shot 2018-01-17 at 15 58 36" src="https://user-images.githubusercontent.com/2635143/35049144-5b3a8e20-fb9f-11e7-9a95-620d91c3f932.png">

```
<style type="text/css" data-glamor=""></style>
```

Reproduction:

https://glamorous.rocks/ does not have this problem, but if you go to https://github.com/paypal/glamorous/blob/master/other/USERS.md#glamorous-users and take https://budgee.com/ as an example, you can see the same result described above.

**Comment by marzelin** [comment]
`glamorous` uses `glamor` under the hood to append/remove styles. When in production, `glamor` works in 'speedy mode' that uses `insertRule` to add css to the page. This method adds rules directly into `CSSStyleSheet`. That's why you don't see rules in the `<style>` tag in production.

You can learn more in [glamor docs](https://github.com/threepointone/glamor#speedy-mode).

**Comment by davincho** [comment]
Further reference https://bugs.chromium.org/p/chromium/issues/detail?id=387952
