### ISSUE TITLE
Make glamorous faster

### ISSUE THREAD

**Issue by kentcdodds** [paypal/glamorous#43]
We haven't done any benchmarking, but @garetmckinley [is going to](https://twitter.com/garetmckinley/status/851689363050254336):

> I'm going to benchmark glamorous against styled-components this week, so we will see what the numbers say 😊 dont worry, I still love 💅

So let's find bottlenecks and make them faster. There's definitely some low-hanging fruit from my original implementation that didn't need to be that way. Let's start in [the `render`](https://github.com/paypal/glamorous/blob/master/src/index.js#L73-L98) function which is probably the hottest code path of the codebase.

Anyone wanna try setting up some benchmarking to determine our bottlenecks and start speeding things up? Maybe @developit could give us some pointers...

**Comment by kentcdodds** [comment]
I think that we could maybe write a babel plugin to take this:

```javascript
const MyDiv = glamorous.div({padding: 20}, ({big}) => ({fontSize: big ? 20 : 30}))
```

to this:

```javascript
const MyDiv = glamorous.div('css-dfk22d34', ({big}) => ({fontSize: big ? 20 : 30}))
```

Where the static styles are pre-processed and the resulting styles are extracted to a separate stylesheet, and we work with glamor's rehydration API to hook things up again. We'd need to update the `glamorousComponentFactory` API to accept a string class name, but that _should_ be trivial. In any case, this would probably speed things up significantly.

I just realized that based on the way we merge glamor class names with the styles they represent into a single class name may cause issues with this, but let's start with components that have static styles only, then maybe we can get it working with a combination of static and dynamic styles.

Anyone wanna write a plugin for this? If you've not made a Babel plugin before or worked with ASTs before, you can learn about it from [my talk](https://youtu.be/CFQBHy8RCpg?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) :)

**Comment by developit** [comment]
You can skip an object copy by removing [this line](https://github.com/paypal/glamorous/blob/master/src/index.js#L75).  Instead of "plucking" className off of props, simply use `props.className`.  In order to have your custom value take precedence over [`props.className` here](https://github.com/paypal/glamorous/blob/master/src/index.js#L95-L98) just place the inline property after the rest spread.

Other things: remove `map()`.

```js
      render() {
        const props = this.props
        const {toForward, cssOverrides} = splitProps(props, GlamorousComponent)
        const theme = Object.assign({}, this.state.theme)
        // create className to apply
        const mappedArgs = GlamorousComponent.styles.slice();
        for (let i=mappedArgs.length; i--; ) {
          if (typeof mappedArgs[i]==='function') {
            mappedArgs[i] = mappedArgs[i](props, theme);
          }
        }
        const {
          glamorStyles: parentGlamorStyles,
          glamorlessClassName,
        } = extractGlamorStyles(props.className)
        const glamorClassName = css(
          ...mappedArgs,
          ...parentGlamorStyles,
          cssOverrides,
        ).toString()
        const fullClassName = joinClasses(glamorlessClassName, glamorClassName)

        return React.createElement(GlamorousComponent.comp, {
          ...toForward,
          className: fullClassName,
        })
      }

```

**Comment by kentcdodds** [comment]
Dude, you're the best, thanks for that @developit! Anyone wanna actually make these changes?

**Comment by kkemple** [comment]
i'll jump on it if no one else wants to do it, will let it sit for a day to see if anyone else wants to try. :smile:

**Comment by kentcdodds** [comment]
Thanks @kkemple! I tweeted it out. We'll see if anyone else is interested in jumping on board.

**Comment by kkemple** [comment]
🎣

**Comment by garetmckinley** [comment]
I watched your talk about ASTs Kent. Supppppper informative! I've been wanting to dig into babel plugins for a little while. Was moderately disappointed when I realized frontend masters didn't have a course on ASTs or babel plugins, so your video was exactly the introduction I was looking for 💣  you have an awesome way of teaching that really makes information stick. Too many educators use a very "formal" way of teaching, but you walk us through figuring stuff out by console logging and using actual debugging tools.

That said, I want to take a whack at making a babel plugin for glamorous. If I read your message correctly, you're saying that it's not totally possible at the moment with glamorous due to the `glamorousComponentFactory` API, but that shouldn't stop me from being able to generate classes and mapping them to the component factory, right?

If somebody more experienced than me wants to create it, that's fine. But I'm going to treat creating a glamorous plugin as my introductory project to babel plugins. The only thing I'm unsure about is how to go about generating an eternal stylesheet to rehydrate glamorous with. I'll have to dig through the source a bit, it would be awesome if I could get pointed in the right direction 😄

**Comment by kentcdodds** [comment]
> Was moderately disappointed when I realized frontend masters didn't have a course on ASTs or babel plugins

Fun fact, I'm giving an [asts-workshop at Frontend Masters](https://frontendmasters.com/workshops/code-transformation-linting-asts/) in 1.5 weeks!

I'm glad the video was helpful. And thanks so much for the feedback :)

> If I read your message correctly, you're saying that it's not totally possible at the moment with glamorous due to the glamorousComponentFactory API, but that shouldn't stop me from being able to generate classes and mapping them to the component factory, right?

Correct. We can make the API changes separately. You can go ahead and start work on the babel plugin as soon as you want.

> The only thing I'm unsure about is how to go about generating an eternal stylesheet to rehydrate glamorous with.

Yeah, this bit will be a little tricky, but it actually seems like you could take some inspiration from the plugin by @thejameskyle called [babel-plugin-polished](https://github.com/styled-components/babel-plugin-polished). Basically, when you find the right object literal, you require in `glamor` and run it on that object literal. The part where you'll divert from the polished plugin is that when the plugin's finished with a file, it'll need to save the CSS to another file somewhere. It may be a little tricky. Maybe @threepointone will have some tips...

I think this could be a really awesome plugin. Super cool experience for anyone wanting to get into this stuff.

> also I've been real busy with my day job this week, but I'll hopefully be able to get back to working on those benchmarks tonight. If not tonight, definitely this weekend.

Hey man, don't overwork yourself. This is open source, if you can't do it, no biggie. Other people can make their own stuff if they really need to :) Thanks for any work you're able to do!

**Comment by edygar** [comment]
I've tried to add glamorous in [this benchmark](https://github.com/necolas/react-native-web/tree/master/performance) but something went really wrong, maybe just because I'm unexperienced. Have any of you tried?

**Comment by kentcdodds** [comment]
Hey @edygar! Thanks for trying that. I haven't tried that out yet. I've not really done much actual benchmarking yet :-/

**Comment by kentcdodds** [comment]
I should also mention that I'm less interested in benchmarking against other solutions and more interested in benchmarking against ourselves so we can see our own improvement.

**Comment by tkh44** [comment]
@kentcdodds I collected some rough data and put it into a spreadsheet [here](https://docs.google.com/spreadsheets/d/18QzVqCs4rfLt_BJqW5Z2I7rtQieGo7L74FHzePMbWcI/edit?usp=sharing).

I used this little code snippet and checked dev tools profiles to get the data. I'm not sure how valuable this is but it's something 🙂
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Glamorous Render Test</title>
</head>
<body>
<div id="target"></div>
<script src="../node_modules/react/dist/react.js"></script>
<script src="../node_modules/react-dom/dist/react-dom.js"></script>
<script src="../node_modules/glamor/umd/index.min.js"></script>
<script src="../dist/glamorous.umd.js"></script>
<script type="text/javascript">
    'use strict';
  const Test = glamorous.div(({ i }) => ({
    background: '#f06595',
    borderBottom: '1px solid #a61e4d',
    height: 100,
    order: i,
    width: 100,
  }));

//  const Test = ({ i }) => {
//    return React.createElement(
//      'div',
//      {
//        style: {
//          background: '#f06595',
//          borderBottom: '1px solid #a61e4d',
//          height: 100,
//          order: i,
//          width: 100,
//        }
//      }
//    );
//  }

  const target = document.getElementById('target')
  console.profile();
  ReactDOM.render(
    React.createElement(
      glamorous.Div,
      {
//        css: {
//          '& > div': { marginBottom: 4 },
//          display: 'flex',
//          flexDirection: 'column',
//          alignItems: 'center'
//        }
      },
      Array.from({ length: 1000 }, (_, i) => React.createElement(Test, { i: i, key: i}))
    ),
    target
  );
  console.profileEnd();
</script>
</body>
</html>
```

**Comment by kentcdodds** [comment]
Awesome! I wonder whether there's any way we can automate the generation of this data so we could add a log in our Travis CI to indicate whether we're faster or slower than master. May be kinda hard to do well though :-/

**Comment by tkh44** [comment]
@kentcdodds These numbers look grim until you realize that glamor is generating 1000 different classes. FWIW I've dug into the profiler and tried to pin down anything in glamorous that is the bottleneck and the biggest hot spots are in `get-glamorous-classname.js`. And the source of these hotspots is... glamor 😄 
![image](https://cloud.githubusercontent.com/assets/662750/25353374/402556b4-28ec-11e7-8f62-1a8bf4d3afe5.png)

The only deopt I could find were in `fast-memoize`'s `variadic` function. I'm guessing due to `Array.prototype.slice.call(arguments, 3)`. If we know the arg length ahead of time why not write our own?

```js
function variadic (fn, cache, serializer, arg1, arg2) {
  var args = [arg1, arg2]
  var cacheKey = serializer(args)

  if (!cache.has(cacheKey)) {
    var computedValue = fn.apply(this, args)
    cache.set(cacheKey, computedValue)
    return computedValue
  }

  return cache.get(cacheKey)
}

function strategy (fn, options) {
  return variadic.bind(
    this,
    fn,
    options.cache.create(),
    options.serializer
  )
}


memoize(shouldForwardProperty, { strategy })
```

Not even sure if it is worth the effort though.

**Comment by kentcdodds** [comment]
Thanks for digging into that even further! Honestly, I think that it may be even better for us to see big applications built with glamorous and see how it performs in those cases. It's harder, but those are the benchmarks that really matter.

Considering that this is kind of an ongoing effort and I don't see any more big wins we can make here, I'm going to go ahead and close this and say that we're as fast as we need to be <3

Thanks everyone!

**Comment by kentcdodds** [comment]
Not to stifle innovation! Happy to review PRs to make things faster so long as it doesn't make things too complicated :)
